### PR TITLE
Bank  account created

### LINKED ISSUE #1: Creation of  abstract BankAccount class
**What to build**
Create the BankAccount abstract class in the banking.model package. This is the foundation of the entire project. Every other class in the model package depends on this one being correct. Take your time with it.
Done when:

- •	Class is abstract — the compiler should reject new BankAccount(...) anywhere in the code
- •	Private fields: accountNumber (String), ownerName (String), balance (double)
- •	Private List<Transaction> initialised as new ArrayList<>() in the constructor
- •	Constructor takes accountNumber, ownerName, initialBalance and sets all three
- •	Public getters for accountNumber, ownerName, balance, and transactions
- •	Protected deductFromBalance(double amount) method — subclasses need this
- •	Abstract method declaration: public abstract void withdraw(double amount) throws InsufficientFundsException
- •	Concrete deposit(double amount): validates amount > 0, adds to balance, creates and adds a Transaction
- •	printStatement() prints the last 5 transactions or all if fewer than 5 exist

**Why this matters:**
The abstract class pattern models the real world accurately: there is no such thing as a plain 'bank account' — it is always a specific type. Making this abstract forces every subclass to implement its own withdrawal rules.

### PR DESCRIPTION
**Pull request by sngatane**
In ticket 1 created the Abstract class in the banking.model package. The abstract class pattern models the real world accurately as the simple "Bank Account" does not exist. It always is quite specific. Making this abstract ensures that every subclass implements  its own withdrawal rules.

### CODE REVIEW

File: Banking/model/BankAccount.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+
+    public void printStatement() {
+        System.out.println("\n--- Last Transactions ---");
+
+        if (transactions.isEmpty()) {
+            System.out.println("No transactions yet.");
+            return;
+        }
+
+        int startIndex = transactions.size() - 5;
```
Comment (Uyanda-shabalala) [inline Banking/model/BankAccount.java:67]: please just inialize to zero or just declare the variable without initialising

**Review by Uyanda-shabalala — CHANGES_REQUESTED** [review]
